# Generated by Django 6.0.3 on 2026-04-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0017_alter_certificado_imagem_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='foto',
            field=models.ImageField(upload_to='Perfil'),
        ),
    ]
