# Generated by Django 6.0.3 on 2026-05-15 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0018_alter_inicio_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Digite no formato: (12) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')])),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
