# Generated by Django 6.0.3 on 2026-05-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0019_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
